### ISSUE TITLE
Totally newbie questions

### ISSUE THREAD

**Issue by sagonzal** [Overdrivr/Telemetry#55]
First Rémi, let me say that I congratulate you for your extremely hard work towards this really useful library. I found telemetry on my personal intent to re-invent the wheel ONCE more. So thank, you and if you help me I will work towards improving and porting your library.

I ported telemetry (plain C) to the K22FN512 (a cortex M4 cpu) platform on the K22F freedom board. I took me a week since I was not very sure how is the actual output string were and how the output should look on the debug serial port I use.

So my first questions are:

_(1)_ Which is the minimal code to port ? I asked this because I have to rewrote the following routines:

void newentry_u8(FILE \* file, const char \* topic, uint8_t data)
{
  fputs("u8", file);
  fputs("\t;\t", file);
  fputs(topic, file);
  fputs("\t;\t", file);
  fprintf(file, "%hhu", data);
  fputs("\t;\t", file);
  publish_u8(topic,data);
  fputs("\n", file);
}

into this:

void newentry_u8(FILE \* file, const char \* topic, uint8_t data)
{
    PRINTF("u8");
    PRINTF("\t;\t");
    PRINTF(topic);
    PRINTF("\t;\t");
    PRINTF("%hhu", data);
    PRINTF("\t;\t");
    publish_u8(topic,data);
    PRINTF("\n");
}

...since my platform does not support fputs.

Is there a more elegant way to do this in Telemetry?

Another issue is the following setup in main:
    //
    // Telemetry setup
    //
    transport.write = tlm_write;
    transport.read = tlm_read;

then I also rewrote:

int32_t tlm_write(void \* buf, uint32_t sizeToWrite)
{
  uint8_t \* caster = (uint8_t*)(buf);
  uint32_t i;
  for(i = 0 ; i < sizeToWrite ; i++)
  {
//      fprintf(output, "%02x", caster[i]);
      PRINTF("%02x", caster[i]);
  }
}

_(2)_ In the examples you open a file and use fprintf and that is why you use output. Is this necessary ?
  In the example:

```
output = fopen("valid_vectors.csv", "w");
if (output == NULL) {
    printf("Failure : Could not open file for write.");
    return -1;
}
```

_(3)_ Can we mix messages ? What I mean with this is that I was planing to use serial as I always do with "general" debug information and plus Telemetry. is this possible, pyTelemetry wont get confused ?

For example this is a direct example of what I'm having now:

```
Actual dip-switch status is 15 

f70100746f706963008a56c77f

Initiating TMP175 temperature read.

Ch.0 (0x 38E), Ch.1 (0x 455) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f706963008b56477f

Initiating TMP175 temperature read.

Ch.0 (0x 3D5), Ch.1 (0x 4C9) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f706963008c357df77f

Initiating TMP175 temperature read.

Ch.0 (0x 228), Ch.1 (0x 3BD) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f706963008d35777f

Initiating TMP175 temperature read.

Ch.0 (0x 251), Ch.1 (0x 4D0) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f706963008e14e77f

Initiating TMP175 temperature read.

Ch.0 (0x 38F), Ch.1 (0x 455) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f706963008f14677f

Initiating TMP175 temperature read.

Ch.0 (0x 24F), Ch.1 (0x 4D3) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f7069630090fb167f

Initiating TMP175 temperature read.

Ch.0 (0x 3BE), Ch.1 (0x 55E) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f7069630091fb967f

Initiating TMP175 temperature read.

Ch.0 (0x 28B), Ch.1 (0x 3D4) 

Temp (0x4A59) 

 Actual dip-switch status is 15 

f70100746f7069630092da067f

Initiating TMP175 temperature read.
```

As you can see Telemetry output is inserted in the middle. Will this work as intended in pyTelemetry ?

**Comment by Overdrivr** [comment]
Hi ! Thanks for the feedback. I'll try to clarify all those things a bit.

(1)
The code where you replaced `fputs` by `fprintf` is part of the tests, that is meant to be run on your computer, not on the embedded board. So you should not worry about it, nor need to replace fputs by fprintf.

(2) 
Also related to testing, it is not an example. I have setup a repository dedicated to examples (I don't I have mentionned it enough in the documentation)
[https://github.com/Overdrivr/Telemetry-examples]
Sadly, there is not plain-c example yet. I you provide me a bare-metal UART library for K22FN512, I can push an example on this repo

(3)
Yes, this won't cause any trouble. Pytelemetry delimits frames using special values, and checks frame validity using a crc code. Your serial flow won't be affected. 
However, I suppose you would like to get this raw serial output computer-side.
For now, I haven't provided a way to register a python callback when raw, non-telemetry data is received. It is rather easy to do, I just simply did not find the time.

Until then, my best recommandation is to publish on particular topic, `log` for instance, where you will publish all your messages.

```
publish("log", "Actual dip-switch status is 15")
publish("log", "Initiating TMP175 temperature read.");
//etc
```

This way, all your messages computer-side can be easily accessible from telemetry.

Just a quick note, I am currently in the process of simplifying and claryfing a lot the build process, which will make user contributions hell of a lot more easier. Watch for the changes in the repo in the next couple of weeks ;) But I won't break any existing code, just project folder hierarchy, code organization, etc.

In the meantime, let me know if I can help you further, and thank you for your interest in Telemetry !

**Comment by sagonzal** [comment]
Thank you Rémi for your answer.

Regarding (2) I produced a uart.c I used in my own programs in a similar way Liviu Ionescu does using https://github.com/gnuarmeclipse. I can upload to you but I don't know where to place this file in GitHub?

Regarding (3), I was puzzled initially on the so many directories and files Telemetry has, on the embedded app, which is the on one would care about. What I did was to follow this directory structure to import telemetry into my own test program as can be seen in the following images.

for the includes:
![telemetry 01](https://cloud.githubusercontent.com/assets/2891341/15118602/5015c9ae-15e3-11e6-89f6-362b3e382b8a.png)
for the sources:
![telemetry 02](https://cloud.githubusercontent.com/assets/2891341/15118601/501204ea-15e3-11e6-9b01-68d5c30a1cb4.png)

Please notice how I gray-out test and test vectors avoiding compiler to look for them. But when you are new to a library you are importing you have a hard time discovering what to include and what to not.
Since I use automation for creating makefiles by gnuarmeclipse the only way is to separate src and includes as seen on the images.

Thank you again.

**Comment by Overdrivr** [comment]
Hi,

You can have a look at the build-refactoring branch https://github.com/Overdrivr/Telemetry/tree/build-refactoring

When you need to _install_ Telemetry inside an embedded project, it is recommended to go to the [release page](https://github.com/Overdrivr/Telemetry/releases), grab the latest Telemetry-c.zip in your case, decompress and put the files inside your project.
This archive only contains the files you need, not the test files, neither the build script, etc.

FYI, I have moved platform-specific code (Basically, `read`,`write`,`readable` and `writeable` functions with hardware-related code) into dedicated repositories (https://github.com/Overdrivr/Telemetry-arduino and https://github.com/Overdrivr/Telemetry-mbed )

Now, this repo only contains the core library. The consequence is that the folder hierarchy is hugely simplified and you should find it much more readable. User contributions will also be much easier

Regarding your implementation, could you post the uart.c file to a gist (https://gist.github.com/ ) ? This way I can have a look at it.

If you are interested, I can create a repository Telemetry-Kinetis-K22, or, if you wish to contribute to Telemetry, also feel free to create the repository yourself and I will help you out setting things up.

EDIT: Your point regarding some build systems that require splitting up sources and headers is a very good one. I am not sure how I should support it out of the box, I guess for now you did as I would recommend, splitting up files manually and eventually fixing up broken #include directives

**Comment by sagonzal** [comment]
Sorry for the delay.in answering back..

If you help me I can create a minimum example for the Kinetis-K22 processor. I really don't know how to create a repository in GITHUB.

**Comment by Overdrivr** [comment]
Sorry about the (very) late feedback too.

If you don't want to go through the hassle of setting up a project for a K22, I would recommend using [mbed](https://developer.mbed.org/) where Telemetry (and a multitude of other libraries) can be imported without effort.

**Comment by sagonzal** [comment]
Rémi, thank you again!. Once you get used to a library then there are few problems integrating it to your own source. That is the case of Telemetry.

I'm not very attached to using mbed since (as I understand) is a completely on-line development platform. Me and my group can not afford this since we are very attached to more conventional tools (GNU ARM compilers, GNU make, Eclipse, etc. )
